# .github/workflows/push.yml

## name of our action
name: Release

# the event that will trigger the action
on:
    workflow_dispatch:

# what the action will do
jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Prepare repository

            - name: Use Node.js 12.x
              uses: actions/setup-node@v3
              with:
                  node-version: 12.x
            - name: Cache node modules

            - name: Create Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              run: |
                  pnpm install --frozen-lockfile
                  pnpm run release
